### ISSUE TITLE
Example from karax readme: Error: cannot open 'vdom'

### ISSUE THREAD

**Issue by garyrob** [pragmagic/karax#2]
I wanted to give karax a try on my MacBook Pro with Nim 0.16.0 installed, starting with the very first example on the readme, but in iTerm I got:

> $ cd examples/todoapp
> $ nim js todoapp.nim
> Hint: used config file '/usr/local/Cellar/nim/0.16.0/nim/config/nim.cfg' [Conf]
> Hint: system [Processing]
> Hint: todoapp [Processing]
> todoapp.nim(2, 8) Error: cannot open 'vdom'

**Comment by haiodo** [comment]
Hi,
You need to do nimble install from karax root folder.

**Comment by haiodo** [comment]
Fixed readme to include `nimble install` before try demo.

**Comment by Araq** [comment]
> You need to do nimble install from karax root folder.

No you don't. ;-)  But you need Nim's development version (0.16.1) to be able to compile it.

**Comment by haiodo** [comment]
Sorry missed .nims file. But for use in custom apps it is still required I think

**Comment by zacharycarter** [comment]
This is actually still an issue.
Even with a nims file, karax modules are unable to be imported.
